sonar.projectKey=KegelNetzwerk_kegelnetzwerk-web
sonar.organization=kegelnetzwerk

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/components/**,src/app/**/page.tsx,src/app/**/layout.tsx,src/app/**/not-found.tsx,src/app/**/error.tsx,scripts/**
